### ISSUE TITLE
msg: Invalid repository string: "ppa:webupd8team/java"

### ISSUE THREAD

**Issue by amirc** [Stouts/Stouts.elasticsearch#4]
Hi,
I'm trying to run the role on a blank debain-7 gce instance and I get this error:

```
failed: [elasticsearch-1] => (item=ppa:webupd8team/java) => {"failed": true, "item": "ppa:webupd8team/java"}
msg: Invalid repository string: ppa:webupd8team/java
```

Work around:

```
- name: init elasticsearch servers
  hosts: tag_elasticsearch
  sudo: true

  vars:
    elasticsearch_apt_repos: []

  roles:
    - briancoca.oracle_java7
    - Stouts.elasticsearch

```
